import { InicisBankCode } from '../../constants';

const {
  Kdb,
  Ibk,
  Kb,
  Keb,
  Housing,
  ShBank,
  NhBank,
  Nonghyup,
  ChBank,
  Woori,
  Chohung,
  Commercial,
  Sc,
  Hanil,
  Seoul,
  ExShinhan,
  Hanmi,
  Daegu,
  Busan,
  Kwangju,
  Jeju,
  Jeonbuk,
  Kangwon,
  Kyongnam,
  BcCard,
  Cu,
  MutualSavings,
  Citi,
  Hsbc,
  Deutsche,
  AbnAmro,
  JpMorgan,
  MitsubishiTokyo,
  Boa,
  Sj,
  Shinan,
  EPost,
  Hana,
  Peace,
  Shinsegae,
  Shinhan,
  KBank,
  KakaoBank,
  NaverPoint,
  TossMoney,
  SsgMoney,
  LPoint,
  KakaoMoney,
  Payco,
} = InicisBankCode;

const BANK_CODE_DISPLAY_NAME_MAPPER = {
  [Kdb]: '한국산업은행',
  [Ibk]: '기업은행',
  [Kb]: '국민은행',
  [Keb]: '하나은행 (구. 외환)',
  [Housing]: '국민은행 (구. 주택)',
  [ShBank]: '수협중앙회',
  [NhBank]: '농협중앙회',
  [Nonghyup]: '단위농협',
  [ChBank]: '축협중앙회',
  [Woori]: '우리은행',
  [Chohung]: '구)조흥은행',
  [Commercial]: '상업은행',
  [Sc]: 'SC제일은행',
  [Hanil]: '한일은행',
  [Seoul]: '서울은행',
  [ExShinhan]: '구)신한은행',
  [Hanmi]: '한국씨티은행 (구. 한미)',
  [Daegu]: '대구은행',
  [Busan]: '부산은행',
  [Kwangju]: '광주은행',
  [Jeju]: '제주은행',
  [Jeonbuk]: '전북은행',
  [Kangwon]: '강원은행',
  [Kyongnam]: '경남은행',
  [BcCard]: '비씨카드',
  [Cu]: '신용협동조합중앙회',
  [MutualSavings]: '상호저축은행',
  [Citi]: '한국씨티은행',
  [Hsbc]: '홍콩상하이은행',
  [Deutsche]: '도이치은행',
  [AbnAmro]: 'ABN암로',
  [JpMorgan]: 'JP모건',
  [MitsubishiTokyo]: '미쓰비시도쿄은행',
  [Boa]: 'BOA(Bank of America)',
  [Sj]: '산림조합',
  [Shinan]: '신안상호저축은행',
  [EPost]: '우체국',
  [Hana]: '하나은행',
  [Peace]: '평화은행',
  [Shinsegae]: '신세계',
  [Shinhan]: '신한(통합)은행',
  [KBank]: '케이뱅크',
  [KakaoBank]: '카카오뱅크',
  [NaverPoint]: '네이버포인트 (포인트 100% 사용)',
  [TossMoney]: '토스머니 (포인트 100% 사용)',
  [SsgMoney]: 'SSG머니 (포인트 100% 사용)',
  [LPoint]: '엘포인트 (포인트 100% 사용)',
  [KakaoMoney]: '카카오머니',
  [Payco]: '페이조 (포인트 100% 사용)',
};

export const getInicisBankCodeDisplayName = (
  bankCode: InicisBankCode
): string => BANK_CODE_DISPLAY_NAME_MAPPER[bankCode];
