export enum GoPayMethod {
  Card = 'Card',
  DirectBank = 'DirectBank',
  VBank = 'VBank',
  HPP = 'HPP',
  PhoneBill = 'PhoneBill',
  Culture = 'Culture',
  DGCL = 'DGCL',
  Bcsh = 'Bcsh',
  HPMN = 'HPMN',
  Kpay = 'Kpay',
  TeenCash = 'TeenCash',
  Paypin = 'Paypin',
  OCBPoint = 'OCBPoint',
  POINT = 'POINT',
  GiftCard = 'GiftCard',
}
